""""Constants"""
# screen specs
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"

# paddle specs
PADDLE_SHAPE = "square"
PADDLE_COLOUR = "white"
PADDLE_LENGTH = 3
PADDLE_STRETCH_WIDTH = 5
FIRST_PADDLE_XCOOR = 350
FIRST_PADDLE_YCOOR = 0
SECOND_PADDLE_XCOOR = -350
SECOND_PADDLE_YCOOR = 0
PADDLE_PACE = 20
PADDLE_HALF_HEIGHT = 20 // 2 * PADDLE_STRETCH_WIDTH #20 = default turtle size.
PADDLE_MAX_YCOOR = SCREEN_HEIGHT // 2 - PADDLE_HALF_HEIGHT * 1.5
PADDLE_MIN_YCOOR = - (PADDLE_MAX_YCOOR)
