""""Constants"""
# screen specs
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"

# paddle specs
PADDLE_SHAPE = "square"
PADDLE_COLOUR = "white"
PADDLE_LENGTH = 3
FIRST_PADDLE_XCOOR = 350
FIRST_PADDLE_YCOOR = 0
SECOND_PADDLE_XCOOR = -350
SECOND_PADDLE_YCOOR = 0
