""""Constants"""
# screen specs
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_BACKGROUND_COLOR = "black"
MAX_SCREEN_YCOOR = SCREEN_HEIGHT // 2
MIN_SCREEN_YCOOR = - (MAX_SCREEN_YCOOR)

# middle ground specs
MIDDLE_SPACE = 10

# paddle specs
PADDLE_SHAPE = "square"
PADDLE_COLOUR = "white"
PADDLE_LENGTH = 3
PADDLE_STRETCH_WIDTH = 5
RIGHT_PADDLE_XCOOR = 350
RIGHT_PADDLE_YCOOR = 0
LEFT_PADDLE_XCOOR = -350
LEFT_PADDLE_YCOOR = 0
PADDLE_PACE = 20
PADDLE_HALF_HEIGHT = 20 // 2 * PADDLE_STRETCH_WIDTH #20 = default turtle size.
PADDLE_MAX_YCOOR = SCREEN_HEIGHT // 2 - PADDLE_HALF_HEIGHT * 1.5
PADDLE_MIN_YCOOR = - (PADDLE_MAX_YCOOR)


# ball specs
BALL_SHAPE = "circle"
BALL_COLOR = "orange"
MAX_BALL_XCOOR = SCREEN_WIDTH // 2 - 60
MIN_BALL_XCOOR = - (MAX_BALL_XCOOR)
MAX_BALL_YCOOR = MAX_SCREEN_YCOOR
MIN_BALL_YCOOR = - (MAX_BALL_YCOOR)
